version: '2'

services:
  elasticsearch:
    restart: always
    build: elasticsearch/
    networks:
      - docker_elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ../esdata:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
  logstash:
    restart: always
    build: logstash/
    depends_on:
      - elasticsearch
    networks:
      - docker_elk
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
    environment:
      - LS_HEAP_SIZE=2048m
    command: -f /etc/logstash/conf.d/
  kibana:
    restart: always
    build: kibana/
    depends_on:
      - elasticsearch
    networks:
      - docker_elk
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/:/etc/kibana/

networks:
  docker_elk:
    driver: bridge
